#!/usr/bin/env python3
"""
Test skeleton generator utility.

Generates test skeleton files for tasks in apply-change workflow.
Tests are colocated with source files.

Supports --save-report to emit step reports for report-driven gates.
"""

import os
import re
import sys
import time
from typing import List, Optional, Tuple

# Import step-report utility
try:
    import importlib.util
    _sr_path = os.path.join(os.path.dirname(__file__), "step-report.py")
    if os.path.isfile(_sr_path):
        _sr_spec = importlib.util.spec_from_file_location("step_report", _sr_path)
        _sr_module = importlib.util.module_from_spec(_sr_spec)
        _sr_spec.loader.exec_module(_sr_module)
        save_step_report = _sr_module.save_step_report
        HAS_STEP_REPORT = True
    else:
        HAS_STEP_REPORT = False
except Exception:
    HAS_STEP_REPORT = False

# Import test framework detection
try:
    import importlib.util
    _tf_path = os.path.join(os.path.dirname(__file__), "test-framework.py")
    if os.path.isfile(_tf_path):
        _spec = importlib.util.spec_from_file_location("test_framework", _tf_path)
        _tf_module = importlib.util.module_from_spec(_spec)
        _spec.loader.exec_module(_tf_module)
        detect_test_framework = _tf_module.detect_test_framework
        HAS_TEST_FRAMEWORK = True
    else:
        HAS_TEST_FRAMEWORK = False
except Exception:
    HAS_TEST_FRAMEWORK = False


def generate_test_skeleton(
    task: str,
    source_file: str,
    framework: str,
    change_name: str,
    task_number: int = 1,
    test_reports_dir: Optional[str] = None
) -> str:
    """
    Generate a test skeleton file for a task.

    Args:
        task: Task description.
        source_file: Path to the source file being tested.
        framework: Test framework (jest, vitest, pytest, cargo-test).
        change_name: OpenSpec change name.
        task_number: Task number for documentation.
        test_reports_dir: Optional directory for test reports.

    Returns:
        Path to the generated test file.

    Test file location (colocated with source):
        - Jest/Vitest: src/auth.js -> src/auth.test.js
        - pytest: src/auth.py -> src/test_auth.py
        - Rust: src/auth.rs -> src/auth_test.rs
    """
    # Determine test file path
    test_file = map_source_to_test_file(source_file)

    # Skip if test file already exists
    if os.path.isfile(test_file):
        return test_file

    # Generate content based on framework
    if framework in ("jest", "vitest", "mocha"):
        content = generate_jest_content(task, source_file, change_name, task_number)
    elif framework in ("pytest", "unittest", "nose"):
        content = generate_pytest_content(task, source_file, change_name, task_number)
    elif framework == "cargo-test":
        content = generate_rust_content(task, source_file, change_name, task_number)
    else:
        # Unknown framework - generate placeholder
        content = generate_placeholder_content(task, source_file, change_name, task_number)

    # Write test file
    os.makedirs(os.path.dirname(test_file), exist_ok=True)
    with open(test_file, "w", encoding="utf-8") as f:
        f.write(content)

    # Update test cases report if directory provided
    if test_reports_dir:
        update_test_cases_report(test_reports_dir, change_name, task, framework, test_file)

    return test_file


def map_source_to_test_file(source_file: str) -> str:
    """
    Map source file to test file path in same directory.

    Examples:
        src/routes/auth.js -> src/routes/auth.test.js
        src/auth.py -> src/test_auth.py
        src/auth.rs -> src/auth_test.rs
    """
    basename = os.path.basename(source_file)
    name, ext = os.path.splitext(basename)
    dir_path = os.path.dirname(source_file)

    if ext == '.py':
        test_name = f"test_{name}.py"
    elif ext == '.rs':
        test_name = f"{name}_test.rs"
    else:
        test_name = f"{name}.test{ext}"

    return os.path.join(dir_path, test_name)


def generate_jest_content(
    task: str,
    source_file: str,
    change_name: str,
    task_number: int
) -> str:
    """Generate Jest/Vitest test content."""
    basename = os.path.basename(source_file)
    name, ext = os.path.splitext(basename)
    keywords = extract_keywords(task)
    primary_kw = keywords[0] if keywords else "feature"

    return f"""// {name}.test{ext}
// Auto-generated by wps-claude-plugin
// Change: {change_name}
// Task {task_number}: {task}

describe('{name}', () => {{

  // === Task {task_number}: {task} ===

  describe('{task}', () => {{

    // --- Happy Path ---
    test('should correctly handle {primary_kw}', () => {{
      // Arrange
      // Act
      // Assert
      expect(true).toBe(true); // TODO: Replace with actual test
    }});

    // --- Error Cases ---
    test('should handle invalid {primary_kw} gracefully', () => {{
      // Arrange
      // Act & Assert
      expect(() => {{
        // call with invalid input
      }}).toThrow();
    }});

    // --- Edge Cases ---
    test('should handle empty/null {primary_kw}', () => {{
      // Arrange
      // Act
      // Assert
      expect(true).toBe(true); // TODO: Replace with actual test
    }});

  }});

}});
"""


def generate_pytest_content(
    task: str,
    source_file: str,
    change_name: str,
    task_number: int
) -> str:
    """Generate pytest test content."""
    basename = os.path.basename(source_file)
    name, ext = os.path.splitext(basename)
    keywords = extract_keywords(task)
    primary_kw = keywords[0] if keywords else "feature"
    class_name = "".join(word.capitalize() for word in name.split("_"))

    return f"""# test_{name}.py
# Auto-generated by wps-claude-plugin
# Change: {change_name}
# Task {task_number}: {task}

import pytest
from unittest.mock import Mock, patch


class Test{class_name}:
    \"\"\"Tests for {name} module.\"\"\"

    # === Task {task_number}: {task} ===

    def test_handles_{primary_kw}_correctly(self):
        \"\"\"Test that {primary_kw} is handled correctly.\"\"\"
        # Arrange
        # Act
        # Assert
        assert True  # TODO: Replace with actual test

    def test_handles_invalid_{primary_kw}(self):
        \"\"\"Test that invalid {primary_kw} is handled gracefully.\"\"\"
        # Arrange
        # Act & Assert
        # with pytest.raises(ValueError):
        #     function_under_test(invalid_input)
        assert True  # TODO: Replace with actual test

    def test_handles_empty_{primary_kw}(self):
        \"\"\"Test that empty/null {primary_kw} is handled correctly.\"\"\"
        # Arrange & Act & Assert
        assert True  # TODO: Replace with actual test


# === Integration Tests ===

class Test{class_name}Integration:
    \"\"\"Integration tests for {name}.\"\"\"

    def test_end_to_end_flow(self):
        \"\"\"Test the complete flow for {task}.\"\"\"
        # Arrange
        # Act
        # Assert
        assert True  # TODO: Replace with actual test
"""


def generate_rust_content(
    task: str,
    source_file: str,
    change_name: str,
    task_number: int
) -> str:
    """Generate Rust test content."""
    basename = os.path.basename(source_file)
    name, ext = os.path.splitext(basename)
    keywords = extract_keywords(task)
    primary_kw = keywords[0] if keywords else "feature"
    test_fn_name = "_".join(primary_kw.split()[:2]) if " " in primary_kw else primary_kw

    return f"""// {name}_test.rs
// Auto-generated by wps-claude-plugin
// Change: {change_name}
// Task {task_number}: {task}

#[path = "{name}.rs"]
mod {name};

#[cfg(test)]
mod tests {{
    use super::{name}::*;

    // === Task {task_number}: {task} ===

    #[test]
    fn test_{test_fn_name}() {{
        // Arrange
        // Act
        // Assert
    }}

    #[test]
    #[should_panic]
    fn test_handles_invalid_input() {{
        // Arrange
        // Act - should panic
    }}

    #[test]
    fn test_handles_edge_case() {{
        // Arrange
        // Act
        // Assert
    }}
}}
"""


def generate_placeholder_content(
    task: str,
    source_file: str,
    change_name: str,
    task_number: int
) -> str:
    """Generate placeholder content for unknown frameworks."""
    basename = os.path.basename(source_file)
    return f"""# Test file for {basename}
# Auto-generated by wps-claude-plugin
# Change: {change_name}
# Task {task_number}: {task}
# Framework: unknown

# TODO: Implement tests for the task above.
# Detected source file: {source_file}
"""


def extract_keywords(task: str) -> List[str]:
    """Extract key nouns/concepts from task description."""
    stop_words = {
        "a", "an", "the", "and", "or", "but", "in", "on", "at", "to", "for",
        "of", "with", "by", "from", "is", "are", "was", "were", "be", "been",
        "being", "have", "has", "had", "do", "does", "did", "will", "would",
        "could", "should", "may", "might", "shall", "can", "set", "add",
        "implement", "create", "setup", "write", "build", "configure",
    }

    words = re.split(r"[\s/\-(),]+", task.lower())
    keywords = []
    seen = set()

    for word in words:
        word = word.strip()
        if len(word) >= 3 and word not in stop_words and word not in seen:
            keywords.append(word)
            seen.add(word)

    return keywords


def update_test_cases_report(
    test_reports_dir: str,
    change_name: str,
    task: str,
    framework: str,
    test_file: str
) -> None:
    """Update test cases markdown report."""
    os.makedirs(test_reports_dir, exist_ok=True)
    report_path = os.path.join(test_reports_dir, f"test-cases-{change_name}.md")

    # Check if report exists
    if not os.path.isfile(report_path):
        lines = [
            f"# Test Cases: {change_name}",
            "",
            f"> Framework: {framework}",
            "> Generated: auto",
            "",
            "## Test Cases by Task",
            "",
        ]
    else:
        with open(report_path, "r", encoding="utf-8") as f:
            lines = f.read().split("\n")

    # Add new task entry
    keywords = extract_keywords(task)
    new_entry = [
        f"### Task: {task}",
        "",
        f"**Test file**: `{os.path.basename(test_file)}`",
        "",
        "#### Unit Tests",
    ]
    for i, kw in enumerate(keywords[:3], 1):
        new_entry.append(f"- [ ] Test {i}: Should correctly handle {kw}")
    new_entry.extend([
        "",
        "---",
        "",
    ])

    # Append if not already present
    if f"### Task: {task}" not in "\n".join(lines):
        # Remove trailing separator if exists
        if lines and lines[-1] == "":
            lines = lines[:-1]
        lines.extend(new_entry)

        with open(report_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))


# CLI interface
if __name__ == "__main__":
    import argparse
    import json

    parser = argparse.ArgumentParser(description="Generate test skeleton")
    parser.add_argument("task", help="Task description")
    parser.add_argument("source_file", help="Source file to test")
    parser.add_argument("--framework", help="Test framework")
    parser.add_argument("--change", required=True, help="Change name")
    parser.add_argument("--task-number", type=int, default=1, help="Task number")
    parser.add_argument("--test-reports-dir", help="Test reports directory")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    parser.add_argument("--save-report", action="store_true",
                        help="Save step report for report-driven gates")
    parser.add_argument("--task-id", help="Task ID for report filename")
    parser.add_argument("--project-root", default=".", help="Project root")

    args = parser.parse_args()

    start_time = time.time()

    # Detect framework if not provided
    framework = args.framework
    if not framework and HAS_TEST_FRAMEWORK:
        project_root = os.path.dirname(args.source_file)
        # Walk up to find project root
        while project_root and not os.path.isfile(os.path.join(project_root, "package.json")):
            parent = os.path.dirname(project_root)
            if parent == project_root:
                break
            project_root = parent
        framework, _ = detect_test_framework(project_root or os.getcwd())

    if not framework:
        framework = "unknown"

    test_file = generate_test_skeleton(
        args.task,
        args.source_file,
        framework,
        args.change,
        args.task_number,
        args.test_reports_dir
    )

    elapsed_ms = int((time.time() - start_time) * 1000)

    if args.save_report and HAS_STEP_REPORT and args.change:
        task_id = args.task_id or str(args.task_number)
        save_step_report(
            change=args.change,
            task_id=task_id,
            step="skeleton",
            status="pass",
            details={
                "test_file": test_file,
                "framework": framework,
                "source_file": args.source_file,
            },
            project_root=args.project_root,
            duration_ms=elapsed_ms,
        )

    if args.json:
        print(json.dumps({
            "test_file": test_file,
            "framework": framework,
        }))
    else:
        print(f"Generated: {test_file}")
        print(f"Framework: {framework}")
