#!/usr/bin/env python3
# Test file for on-user-prompt.py
# Auto-generated by wps-claude-plugin
# Change: optimize-user-prompt-router
# Task 1: Implement IntentClassifier class
# Framework: unittest

import unittest
import sys
import os
import shutil
import importlib.util

# Load the module from file (due to dash in filename)
hooks_dir = os.path.dirname(os.path.abspath(__file__))
module_path = os.path.join(hooks_dir, "on-user-prompt.py")

spec = importlib.util.spec_from_file_location("on_user_prompt", module_path)
on_user_prompt = importlib.util.module_from_spec(spec)
spec.loader.exec_module(on_user_prompt)

IntentClassifier = on_user_prompt.IntentClassifier
IntentResult = on_user_prompt.IntentResult
StateAnalyzer = on_user_prompt.StateAnalyzer
ChangeInfo = on_user_prompt.ChangeInfo
Router = on_user_prompt.Router
RouteDecision = on_user_prompt.RouteDecision
OutputBuilder = on_user_prompt.OutputBuilder


class TestRouter(unittest.TestCase):
    """Tests for Router class."""

    def setUp(self):
        self.router = Router()

    def _make_intent(
        self,
        intent_type="implement",
        confidence="high",
        scope="medium",
        is_trivial_fix=False
    ):
        """Helper to create IntentResult."""
        return IntentResult(
            intent_type=intent_type,
            confidence=confidence,
            scope=scope,
            is_trivial_fix=is_trivial_fix,
            matched_keywords=[]
        )

    def _make_change(
        self,
        name="test-change",
        stage="tasks",
        tasks_total=5,
        tasks_done=0
    ):
        """Helper to create ChangeInfo."""
        return ChangeInfo(
            name=name,
            path="/path/to/change",
            stage=stage,
            tasks_total=tasks_total,
            tasks_done=tasks_done
        )

    # === Task 3.1-3.2: RouteDecision and Router class ===

    def test_router_creation(self):
        """Test Router can be created."""
        router = Router()
        self.assertIsNotNone(router)

    def test_route_decision_creation(self):
        """Test RouteDecision can be created."""
        decision = RouteDecision(
            action="explore",
            mode="auto",
            reason="test reason",
            options=[]
        )
        self.assertEqual(decision.action, "explore")
        self.assertEqual(decision.mode, "auto")

    # === Task 3.3: Question/explore intents (always direct) ===

    def test_route_question_direct(self):
        """Test question intent routes to direct."""
        intent = self._make_intent(intent_type="question")
        decision = self.router.decide(intent, [])
        self.assertEqual(decision.action, "direct")
        self.assertEqual(decision.mode, "direct")

    def test_route_explore_direct(self):
        """Test explore intent routes to direct."""
        intent = self._make_intent(intent_type="explore")
        decision = self.router.decide(intent, [])
        self.assertEqual(decision.action, "direct")
        self.assertEqual(decision.mode, "direct")

    # === Task 3.4: Fix intent (trivial vs non-trivial) ===

    def test_route_fix_trivial_high_confidence_auto(self):
        """Test trivial fix with high confidence auto-routes to direct."""
        intent = self._make_intent(intent_type="fix", confidence="high", is_trivial_fix=True)
        decision = self.router.decide(intent, [])
        self.assertEqual(decision.action, "direct")
        self.assertEqual(decision.mode, "auto")

    def test_route_fix_trivial_medium_confidence_suggest(self):
        """Test trivial fix with medium confidence suggests."""
        intent = self._make_intent(intent_type="fix", confidence="medium", is_trivial_fix=True)
        decision = self.router.decide(intent, [])
        self.assertEqual(decision.action, "direct")
        self.assertEqual(decision.mode, "suggest")

    def test_route_fix_non_trivial_no_change_suggest_explore(self):
        """Test non-trivial fix without active change suggests explore."""
        intent = self._make_intent(intent_type="fix", confidence="high", is_trivial_fix=False)
        decision = self.router.decide(intent, [])
        self.assertEqual(decision.action, "explore")
        self.assertEqual(decision.mode, "suggest")

    # === Task 3.5: Implement intent (auto vs suggest) ===

    def test_route_implement_no_change_high_conf_auto_explore(self):
        """Test implement without change auto-routes to explore."""
        intent = self._make_intent(intent_type="implement", confidence="high", scope="medium")
        decision = self.router.decide(intent, [])
        self.assertEqual(decision.action, "explore")
        self.assertEqual(decision.mode, "auto")

    def test_route_implement_no_change_medium_conf_suggest(self):
        """Test implement without change medium confidence suggests."""
        intent = self._make_intent(intent_type="implement", confidence="medium", scope="medium")
        decision = self.router.decide(intent, [])
        self.assertEqual(decision.action, "explore")
        self.assertEqual(decision.mode, "suggest")

    def test_route_implement_with_active_change_auto_apply(self):
        """Test implement with active change in progress auto-routes to apply-change."""
        intent = self._make_intent(intent_type="implement", confidence="high")
        change = self._make_change(tasks_total=5, tasks_done=2)  # In progress
        decision = self.router.decide(intent, [change])
        self.assertEqual(decision.action, "apply-change")
        self.assertEqual(decision.mode, "auto")

    def test_route_implement_with_complete_change_suggest_archive(self):
        """Test implement with complete change suggests archive."""
        intent = self._make_intent(intent_type="implement", confidence="high")
        change = self._make_change(tasks_total=5, tasks_done=5)  # Complete
        decision = self.router.decide(intent, [change])
        self.assertEqual(decision.action, "archive")
        self.assertEqual(decision.mode, "suggest")

    # === Task 3.6: Archive intent ===

    def test_route_archive_no_changes_direct(self):
        """Test archive with no changes routes to direct."""
        intent = self._make_intent(intent_type="archive")
        decision = self.router.decide(intent, [])
        self.assertEqual(decision.action, "direct")

    def test_route_archive_complete_change_auto(self):
        """Test archive with complete change auto-routes."""
        intent = self._make_intent(intent_type="archive", confidence="high")
        change = self._make_change(tasks_total=5, tasks_done=5)
        decision = self.router.decide(intent, [change])
        self.assertEqual(decision.action, "archive")
        self.assertEqual(decision.mode, "auto")

    def test_route_archive_incomplete_change_suggest_apply(self):
        """Test archive with incomplete change suggests apply-change."""
        intent = self._make_intent(intent_type="archive", confidence="high")
        change = self._make_change(tasks_total=5, tasks_done=2)
        decision = self.router.decide(intent, [change])
        self.assertEqual(decision.action, "apply-change")
        self.assertEqual(decision.mode, "suggest")

    # === Task 3.7: Auto-execute condition check ===

    def test_large_scope_not_auto_explore(self):
        """Test large scope doesn't auto-explore."""
        intent = self._make_intent(intent_type="implement", confidence="high", scope="large")
        decision = self.router.decide(intent, [])
        self.assertEqual(decision.mode, "suggest")


class TestStateAnalyzer(unittest.TestCase):
    """Tests for StateAnalyzer class."""

    def setUp(self):
        self.analyzer = StateAnalyzer()
        self.test_cwd = os.path.join(os.path.dirname(__file__), "_test_cwd")
        # Create the openspec/changes structure
        self.changes_dir = os.path.join(self.test_cwd, "openspec", "changes")
        self._cleanup()

    def tearDown(self):
        self._cleanup()

    def _cleanup(self):
        """Clean up test directory."""
        if os.path.isdir(self.test_cwd):
            shutil.rmtree(self.test_cwd, ignore_errors=True)

    def _create_change(self, name, has_proposal=False, has_design=False, has_tasks=False, tasks_content=None):
        """Helper to create a test change directory."""
        change_dir = os.path.join(self.changes_dir, name)
        os.makedirs(change_dir, exist_ok=True)
        if has_proposal:
            with open(os.path.join(change_dir, "proposal.md"), "w", encoding="utf-8") as f:
                f.write("# Proposal\n")
        if has_design:
            with open(os.path.join(change_dir, "design.md"), "w", encoding="utf-8") as f:
                f.write("# Design\n")
        if has_tasks:
            with open(os.path.join(change_dir, "tasks.md"), "w", encoding="utf-8") as f:
                f.write(tasks_content or "# Tasks\n")

    # === Task 2.1: StateAnalyzer class ===

    def test_state_analyzer_creation(self):
        """Test StateAnalyzer can be created."""
        analyzer = StateAnalyzer()
        self.assertIsNotNone(analyzer)

    # === Task 2.2: find_active_changes ===

    def test_find_active_changes_empty(self):
        """Test find_active_changes with no changes directory."""
        result = self.analyzer.find_active_changes(self.test_cwd)
        self.assertEqual(result, [])

    def test_find_active_changes_single(self):
        """Test find_active_changes with single change."""
        self._create_change("test-change", has_proposal=True)
        result = self.analyzer.find_active_changes(self.test_cwd)
        self.assertEqual(len(result), 1)
        self.assertEqual(result[0].name, "test-change")

    def test_find_active_changes_multiple(self):
        """Test find_active_changes with multiple changes."""
        self._create_change("change-1", has_proposal=True)
        self._create_change("change-2", has_design=True)
        result = self.analyzer.find_active_changes(self.test_cwd)
        self.assertEqual(len(result), 2)
        names = [c.name for c in result]
        self.assertIn("change-1", names)
        self.assertIn("change-2", names)

    # === Task 2.3: get_change_stage ===

    def test_get_change_stage_proposal(self):
        """Test stage detection for proposal-only change."""
        self._create_change("prop-only", has_proposal=True)
        change_dir = os.path.join(self.changes_dir, "prop-only")
        stage = self.analyzer.get_change_stage(change_dir)
        self.assertEqual(stage, "proposal")

    def test_get_change_stage_design(self):
        """Test stage detection for design stage."""
        self._create_change("design-stage", has_proposal=True, has_design=True)
        change_dir = os.path.join(self.changes_dir, "design-stage")
        stage = self.analyzer.get_change_stage(change_dir)
        self.assertEqual(stage, "design")

    def test_get_change_stage_tasks(self):
        """Test stage detection for tasks stage."""
        self._create_change("tasks-stage", has_proposal=True, has_design=True, has_tasks=True)
        change_dir = os.path.join(self.changes_dir, "tasks-stage")
        stage = self.analyzer.get_change_stage(change_dir)
        self.assertEqual(stage, "tasks")

    # === Task 2.4: get_tasks_progress ===

    def test_get_tasks_progress_no_tasks(self):
        """Test progress when no tasks.md exists."""
        self._create_change("no-tasks", has_proposal=True)
        change_dir = os.path.join(self.changes_dir, "no-tasks")
        total, done = self.analyzer.get_tasks_progress(change_dir)
        self.assertEqual(total, 0)
        self.assertEqual(done, 0)

    def test_get_tasks_progress_partial(self):
        """Test progress with partial completion."""
        tasks = "# Tasks\n- [ ] Task 1\n- [x] Task 2\n- [ ] Task 3\n"
        self._create_change("partial-tasks", has_tasks=True, tasks_content=tasks)
        change_dir = os.path.join(self.changes_dir, "partial-tasks")
        total, done = self.analyzer.get_tasks_progress(change_dir)
        self.assertEqual(total, 3)
        self.assertEqual(done, 1)

    def test_get_tasks_progress_complete(self):
        """Test progress with all tasks complete."""
        tasks = "# Tasks\n- [x] Task 1\n- [x] Task 2\n- [x] Task 3\n"
        self._create_change("complete-tasks", has_tasks=True, tasks_content=tasks)
        change_dir = os.path.join(self.changes_dir, "complete-tasks")
        total, done = self.analyzer.get_tasks_progress(change_dir)
        self.assertEqual(total, 3)
        self.assertEqual(done, 3)


class TestChangeInfo(unittest.TestCase):
    """Tests for ChangeInfo dataclass."""

    def test_change_info_creation(self):
        """Test ChangeInfo can be created."""
        info = ChangeInfo(
            name="test-change",
            path="/path/to/change",
            stage="tasks",
            tasks_total=5,
            tasks_done=2
        )
        self.assertEqual(info.name, "test-change")
        self.assertEqual(info.stage, "tasks")

    def test_tasks_complete_property(self):
        """Test tasks_complete property."""
        info = ChangeInfo(name="test", path="/path", stage="tasks", tasks_total=5, tasks_done=5)
        self.assertTrue(info.tasks_complete)

        info2 = ChangeInfo(name="test", path="/path", stage="tasks", tasks_total=5, tasks_done=3)
        self.assertFalse(info2.tasks_complete)

    def test_tasks_started_property(self):
        """Test tasks_started property."""
        info = ChangeInfo(name="test", path="/path", stage="tasks", tasks_total=5, tasks_done=2)
        self.assertTrue(info.tasks_started)

        info2 = ChangeInfo(name="test", path="/path", stage="tasks", tasks_total=5, tasks_done=0)
        self.assertFalse(info2.tasks_started)


class TestIntentClassifier(unittest.TestCase):
    """Tests for IntentClassifier class."""

    def setUp(self):
        self.classifier = IntentClassifier()

    # === Task 1.1: Intent patterns ===

    def test_explore_intent_detection(self):
        """Test explore intent detection."""
        result = self.classifier.detect("分析这个模块的结构")
        self.assertEqual(result.intent_type, "explore")

        result = self.classifier.detect("understand the code flow")
        self.assertEqual(result.intent_type, "explore")

    def test_implement_intent_detection(self):
        """Test implement intent detection."""
        result = self.classifier.detect("实现一个新功能")
        self.assertEqual(result.intent_type, "implement")

        result = self.classifier.detect("add a new feature for login")
        self.assertEqual(result.intent_type, "implement")

    def test_fix_intent_detection(self):
        """Test fix intent detection."""
        result = self.classifier.detect("修复这个bug")
        self.assertEqual(result.intent_type, "fix")

        result = self.classifier.detect("fix the null pointer issue")
        self.assertEqual(result.intent_type, "fix")

    def test_archive_intent_detection(self):
        """Test archive intent detection."""
        result = self.classifier.detect("归档这个变更")
        self.assertEqual(result.intent_type, "archive")

        result = self.classifier.detect("finish the implementation")
        self.assertEqual(result.intent_type, "archive")

    def test_question_intent_detection(self):
        """Test question intent detection."""
        result = self.classifier.detect("这个函数是什么意思？")
        self.assertEqual(result.intent_type, "question")

        result = self.classifier.detect("what does this function do?")
        self.assertEqual(result.intent_type, "question")

    # === Task 1.2: Keyword matching with regex ===

    def test_chinese_keyword_matching(self):
        """Test Chinese keyword matching."""
        result = self.classifier.detect("实现添加新功能")
        self.assertEqual(result.intent_type, "implement")
        self.assertGreaterEqual(len(result.matched_keywords), 2)

    def test_english_keyword_matching(self):
        """Test English keyword matching."""
        result = self.classifier.detect("implement and add new feature")
        self.assertEqual(result.intent_type, "implement")
        self.assertGreaterEqual(len(result.matched_keywords), 2)

    def test_mixed_language_matching(self):
        """Test mixed Chinese and English keywords."""
        result = self.classifier.detect("implement 新功能")
        self.assertEqual(result.intent_type, "implement")

    # === Task 1.3: Confidence level calculation ===

    def test_high_confidence_with_multiple_matches(self):
        """Test high confidence when 2+ keyword matches."""
        result = self.classifier.detect("实现添加新功能开发")
        self.assertEqual(result.confidence, "high")

    def test_medium_confidence_with_one_match(self):
        """Test medium confidence when 1 keyword match."""
        result = self.classifier.detect("实现一个功能")
        self.assertEqual(result.confidence, "medium")

    def test_low_confidence_no_match(self):
        """Test low confidence when no keywords match."""
        result = self.classifier.detect("random text without keywords")
        self.assertEqual(result.confidence, "low")
        self.assertEqual(result.intent_type, "question")  # Default fallback

    # === Task 1.4-1.5: Scope estimation ===

    def test_trivial_scope_detection(self):
        """Test trivial scope detection."""
        result = self.classifier.detect("修复typo拼写错误")
        self.assertEqual(result.scope, "trivial")

    def test_small_scope_detection(self):
        """Test small scope detection."""
        result = self.classifier.detect("添加一个简单的函数")
        self.assertEqual(result.scope, "small")

    def test_medium_scope_detection(self):
        """Test medium scope detection (default)."""
        result = self.classifier.detect("实现一个功能")
        self.assertEqual(result.scope, "medium")

    def test_large_scope_detection(self):
        """Test large scope detection."""
        result = self.classifier.detect("重构整个系统架构")
        self.assertEqual(result.scope, "large")

    # === Task 1.6: Trivial fix heuristics ===

    def test_trivial_fix_scope_trivial(self):
        """Test trivial fix detection when scope is trivial."""
        result = self.classifier.detect("修复typo")
        self.assertTrue(result.is_trivial_fix)

    def test_trivial_fix_private_keyword(self):
        """Test trivial fix detection with private keywords."""
        result = self.classifier.detect("修复内部helper函数")
        self.assertTrue(result.is_trivial_fix)

    def test_non_trivial_fix(self):
        """Test non-trivial fix detection."""
        result = self.classifier.detect("实现大型重构")
        # No trivial hints, scope is large, not a fix
        self.assertFalse(result.is_trivial_fix)


class TestIntentResult(unittest.TestCase):
    """Tests for IntentResult dataclass."""

    def test_intent_result_creation(self):
        """Test IntentResult can be created."""
        result = IntentResult(
            intent_type="implement",
            confidence="high",
            scope="medium",
            is_trivial_fix=False,
            matched_keywords=["实现", "添加"]
        )
        self.assertEqual(result.intent_type, "implement")
        self.assertEqual(result.confidence, "high")
        self.assertEqual(result.scope, "medium")
        self.assertFalse(result.is_trivial_fix)
        self.assertEqual(result.matched_keywords, ["实现", "添加"])


class TestOutputBuilder(unittest.TestCase):
    """Tests for OutputBuilder class."""

    def setUp(self):
        self.builder = OutputBuilder()

    def _make_intent(
        self,
        intent_type="implement",
        confidence="high",
        scope="medium",
        is_trivial_fix=False
    ):
        """Helper to create IntentResult."""
        return IntentResult(
            intent_type=intent_type,
            confidence=confidence,
            scope=scope,
            is_trivial_fix=is_trivial_fix,
            matched_keywords=[]
        )

    def _make_decision(
        self,
        action="explore",
        mode="auto",
        reason="test reason",
        options=None
    ):
        """Helper to create RouteDecision."""
        return RouteDecision(
            action=action,
            mode=mode,
            reason=reason,
            options=options or []
        )

    def _make_change(
        self,
        name="test-change",
        stage="tasks",
        tasks_total=5,
        tasks_done=0
    ):
        """Helper to create ChangeInfo."""
        return ChangeInfo(
            name=name,
            path="/path/to/change",
            stage=stage,
            tasks_total=tasks_total,
            tasks_done=tasks_done
        )

    # === Task 4.1: OutputBuilder class ===

    def test_output_builder_creation(self):
        """Test OutputBuilder can be created."""
        builder = OutputBuilder()
        self.assertIsNotNone(builder)

    # === Task 4.2: auto_route format ===

    def test_auto_route_explore(self):
        """Test auto-route format for explore."""
        decision = self._make_decision(action="explore", reason="Test reason")
        output = self.builder.auto_route(decision)
        self.assertIn("Auto-Route: /openspec-explore", output)
        self.assertIn("Reason: Test reason", output)

    def test_auto_route_apply_change(self):
        """Test auto-route format for apply-change."""
        decision = self._make_decision(action="apply-change", reason="Continuing work")
        output = self.builder.auto_route(decision)
        self.assertIn("Auto-Route: /openspec-apply-change", output)

    def test_auto_route_archive(self):
        """Test auto-route format for archive."""
        decision = self._make_decision(action="archive", reason="All complete")
        output = self.builder.auto_route(decision)
        self.assertIn("Auto-Route: /openspec-archive-change", output)

    def test_auto_route_direct(self):
        """Test auto-route format for direct (no skill)."""
        decision = self._make_decision(action="direct", reason="Direct action")
        output = self.builder.auto_route(decision)
        self.assertIn("Direct action", output)
        self.assertNotIn("Auto-Route:", output)

    # === Task 4.3: suggestion format ===

    def test_suggestion_with_options(self):
        """Test suggestion format with options."""
        intent = self._make_intent(intent_type="implement")
        decision = self._make_decision(
            action="explore",
            mode="suggest",
            reason="No active change",
            options=["Option 1", "Option 2"]
        )
        output = self.builder.suggestion(intent, [], decision)
        self.assertIn("Detected intent: **implement**", output)
        self.assertIn("Reason: No active change", output)
        self.assertIn("1. Option 1", output)
        self.assertIn("2. Option 2", output)

    # === Task 4.4: direct format ===

    def test_direct_empty_changes(self):
        """Test direct format with no changes."""
        output = self.builder.direct([])
        self.assertEqual(output, "")

    def test_direct_with_change(self):
        """Test direct format with active change."""
        change = self._make_change(name="test-change", tasks_total=5, tasks_done=2)
        output = self.builder.direct([change])
        self.assertIn("=== OpenSpec Active Changes Detected ===", output)
        self.assertIn("Change: test-change", output)
        self.assertIn("=== Instructions ===", output)

    def test_direct_with_complete_change(self):
        """Test direct format with complete change includes auto-commit."""
        change = self._make_change(name="complete-change", tasks_total=5, tasks_done=5)
        output = self.builder.direct([change])
        self.assertIn("=== Auto-Commit:", output)
        self.assertIn("All 5 tasks", output)

    # === Task 4.5: Preserve existing behavior ===

    def test_direct_preserves_change_info(self):
        """Test direct format preserves change info structure."""
        change = self._make_change(name="my-change", tasks_total=10, tasks_done=3)
        output = self.builder.direct([change])
        # Check structure matches existing behavior
        self.assertIn("Change: my-change", output)
        self.assertIn("Before responding to the user's question:", output)


class TestMainIntegration(unittest.TestCase):
    """Integration tests for main() function (Tasks 5.1-5.4)."""

    # === Task 5.4: Test with various prompt types ===

    def test_implement_intent_routes_correctly(self):
        """Test implement intent produces appropriate routing."""
        classifier = IntentClassifier()
        intent = classifier.detect("实现一个新功能")
        router = Router()
        decision = router.decide(intent, [])

        # Should suggest explore when no active change
        self.assertEqual(decision.action, "explore")

    def test_fix_trivial_routes_directly(self):
        """Test trivial fix routes to direct."""
        classifier = IntentClassifier()
        # Use multiple fix keywords for high confidence: 修复 + 解决
        intent = classifier.detect("修复解决typo拼写错误")
        router = Router()
        decision = router.decide(intent, [])

        # Trivial fix with high confidence should auto-route to direct
        self.assertEqual(decision.action, "direct")
        self.assertEqual(decision.mode, "auto")

    def test_question_routes_directly(self):
        """Test question intent routes directly."""
        classifier = IntentClassifier()
        intent = classifier.detect("这个函数是什么？")
        router = Router()
        decision = router.decide(intent, [])

        self.assertEqual(decision.action, "direct")
        self.assertEqual(decision.mode, "direct")

    def test_explore_routes_directly(self):
        """Test explore intent routes directly."""
        classifier = IntentClassifier()
        intent = classifier.detect("分析这个模块")
        router = Router()
        decision = router.decide(intent, [])

        self.assertEqual(decision.action, "direct")
        self.assertEqual(decision.mode, "direct")

    def test_archive_with_complete_change(self):
        """Test archive intent with complete change."""
        classifier = IntentClassifier()
        intent = classifier.detect("归档这个变更")
        change = ChangeInfo(
            name="test-change",
            path="/path",
            stage="tasks",
            tasks_total=5,
            tasks_done=5
        )
        router = Router()
        decision = router.decide(intent, [change])

        # Should auto-route to archive
        self.assertEqual(decision.action, "archive")

    # === Task 5.3: Backward compatibility ===

    def test_backward_compatible_output_structure(self):
        """Test that direct mode output preserves existing structure."""
        change = ChangeInfo(
            name="test-change",
            path="/path/to/change",
            stage="tasks",
            tasks_total=5,
            tasks_done=2
        )
        builder = OutputBuilder()
        output = builder.direct([change])

        # Should have all existing markers
        self.assertIn("=== OpenSpec Active Changes Detected ===", output)
        self.assertIn("Change: test-change", output)
        self.assertIn("=== Instructions ===", output)
        self.assertIn("Before responding to the user's question:", output)

    def test_backward_compatible_complete_change_output(self):
        """Test that complete change includes auto-commit hint."""
        change = ChangeInfo(
            name="done-change",
            path="/path/to/change",
            stage="tasks",
            tasks_total=3,
            tasks_done=3
        )
        builder = OutputBuilder()
        output = builder.direct([change])

        # Should have auto-commit section
        self.assertIn("=== Auto-Commit:", output)
        self.assertIn("All 3 tasks", output)
        self.assertIn("git status --porcelain", output)

    def test_backward_compatible_empty_output(self):
        """Test that no changes produces empty output."""
        builder = OutputBuilder()
        output = builder.direct([])
        self.assertEqual(output, "")


if __name__ == "__main__":
    unittest.main()
